name: Generate contribution snake

on:
  # run automatically every 6 hours
  schedule:
    - cron: "* */6 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  push:
    branches:
    - master
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates a snake game from a github user contributions graph, output a svg animation at <svg_out_path>
      - name: generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark&color_snake=orange
           
      # push the content of <build_dir> to a branch
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
